kind = "web"
previewPath = "/"
title = "Codingal"
version = "1.0.0"
id = "artifacts/codingal"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18940

[services.development]
run = "pnpm --filter @workspace/codingal run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/codingal", "run", "build" ]
publicDir = "artifacts/codingal/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18940"
BASE_PATH = "/"
